"""心臓MRI TI scoutシミュレータの設定値。"""

# 通常入力
DEFAULT_WEIGHT_A_KG = 50.0
DEFAULT_WEIGHT_B_KG = 70.0
MIN_WEIGHT_KG = 30.0
MAX_WEIGHT_KG = 100.0
WEIGHT_STEP_KG = 1.0

DEFAULT_SCOUT_TIME_MIN = 5.0
MIN_SCOUT_TIME_MIN = 2.0
MAX_SCOUT_TIME_MIN = 15.0
SCOUT_TIME_STEP_MIN = 0.1

DEFAULT_PSIR_TIME_MIN = 8.0
MIN_PSIR_TIME_MIN = MIN_SCOUT_TIME_MIN
MAX_PSIR_TIME_MIN = MAX_SCOUT_TIME_MIN
PSIR_TIME_STEP_MIN = SCOUT_TIME_STEP_MIN

DEFAULT_NATIVE_T1_MS = 1250.0
MIN_NATIVE_T1_MS = 1000.0
MAX_NATIVE_T1_MS = 1600.0
NATIVE_T1_STEP_MS = 10.0

# 第28節 左室血液プール入力
DEFAULT_NATIVE_BLOOD_T1_MS = 1800.0
MIN_NATIVE_BLOOD_T1_MS = 1400.0
MAX_NATIVE_BLOOD_T1_MS = 2200.0
NATIVE_BLOOD_T1_STEP_MS = 10.0

# 自施設の投与条件（ガドビスト濃度は1.0 mmol/mL）
GADOBUTROL_CONCENTRATION_MMOL_PER_ML = 1.0
FIRST_DOSE_MMOL_PER_KG = 0.05
SECOND_TARGET_DOSE_MMOL_PER_KG = 0.15
TARGET_TOTAL_DOSE_MMOL_PER_KG = 0.20
MAX_TOTAL_VOLUME_ML = 10.0
CONTRAST_INJECTION_RATE_ML_S = 2.0
FIRST_INJECTION_TIME_MIN = 0.0
SECOND_INJECTION_TIME_MIN = 2.0
FIRST_SALINE_VOLUME_ML = 20.0
SECOND_SALINE_VOLUME_ML = 35.0
SALINE_INJECTION_RATE_ML_S = 2.0

# 文献データから本アプリ用に算出した係数
DEFAULT_A_PK = 3.82385
DEFAULT_WASHOUT_RATE_PER_MIN = 0.054457
DEFAULT_RELAXIVITY_PER_MMOL_L_S = 5.0

# 文献の平均血液プール濃度3点から本アプリ用に回帰した二次的係数
DEFAULT_A_BLOOD = 5.86776
DEFAULT_BLOOD_WASHOUT_RATE_PER_MIN = 0.07316
DEFAULT_BLOOD_RELAXIVITY_PER_MMOL_L_S = 5.0

# 施設校正およびTI表示
DEFAULT_FACILITY_OFFSET_MS = 57.0
DEFAULT_BLOOD_FACILITY_OFFSET_MS = 0.0
MIN_BLOOD_FACILITY_OFFSET_MS = -100.0
MAX_BLOOD_FACILITY_OFFSET_MS = 100.0
BLOOD_FACILITY_OFFSET_STEP_MS = 1.0
DEFAULT_TI_MIN_MS = 0.0
DEFAULT_TI_MAX_MS = 700.0
DEFAULT_TI_STEP_MS = 1.0

# v2.1 左室短軸イラスト表示
DEFAULT_ILLUSTRATION_TI_MS = 250.0
MIN_ILLUSTRATION_TI_MS = DEFAULT_TI_MIN_MS
MAX_ILLUSTRATION_TI_MS = DEFAULT_TI_MAX_MS
ILLUSTRATION_TI_STEP_MS = 10.0

# 表示桁数（第15節）
DISPLAY_DECIMALS = {
    "volume_ml": 2,
    "injection_duration_s": 2,
    "dose_mmol_per_kg": 3,
    "dose_ratio_percent": 1,
    "concentration_mmol_per_l": 3,
    "t1_ms": 0,
    "null_ti_ms": 0,
    "relative_signal_percent": 1,
}
