import{CONFIG,grayscale,signalAtTi,signalCurve,simulate,myocardialConcentration,postContrastT1,correctedNullTi}from"./model.js";
const $=id=>document.getElementById(id),state={displayTi:CONFIG.ti.default,result:null};
const inputs={weight:$("weight"),scoutAfterSecond:$("scout-time"),psirAfterSecond:$("psir-time"),nativeT1:$("native-t1"),nativeBloodT1:$("native-blood-t1")};
const fmt=(v,d=0)=>Number(v).toFixed(d),signed=v=>`${v>=0?"+":""}${fmt(v)} ms`;
function readInput(){return Object.fromEntries(Object.entries(inputs).map(([k,i])=>[k,Number(i.value)]));}
function reset(){inputs.weight.value=50;inputs.scoutAfterSecond.value=5;inputs.psirAfterSecond.value=8;inputs.nativeT1.value=1250;inputs.nativeBloodT1.value=1800;state.displayTi=250;$("display-ti").value=250;update();}
function renderDose(r){const d=r.dose;$("dose-caption").textContent=`設定体重 ${fmt(r.weight)} kg に対するインジェクター設定値です。`;$("first-volume").textContent=`${fmt(d.firstVolumeMl,1)} mL`;$("second-volume").textContent=`${fmt(d.secondVolumeMl,1)} mL`;$("total-dose").textContent=`${fmt(d.totalDoseMmolPerKg,3)} mmol/kg`;const shortfall=Math.max(0,.2-d.totalDoseMmolPerKg);$("dose-details").innerHTML=`<table><tr><th>項目</th><th>1回目</th><th>2回目</th></tr><tr><td>投与量</td><td>${fmt(d.firstVolumeMl,1)} mL</td><td>${fmt(d.secondVolumeMl,1)} mL</td></tr><tr><td>実投与量</td><td>${fmt(d.firstDoseMmolPerKg,3)}</td><td>${fmt(d.secondDoseMmolPerKg,3)} mmol/kg</td></tr><tr><td>注入時間</td><td>${fmt(d.firstInjectionDurationS,2)} s</td><td>${fmt(d.secondInjectionDurationS,2)} s</td></tr></table><p>${shortfall?`目標を ${fmt(shortfall,3)} mmol/kg下回ります。`:"目標0.200 mmol/kgを満たします。"}</p>`;}
function renderPrimary(r){$("result-caption").textContent=`設定体重 ${fmt(r.weight)} kgで計算した推定値です。`;$("primary-results").innerHTML=`<div class="result-block"><span class="label">TI scout ${fmt(r.scoutAfterSecond,1)}分後の予想心筋null TI</span><strong class="value">${fmt(r.myocardialNullTi)} ms</strong></div><div class="result-block"><span class="label">TI scout ${fmt(r.scoutAfterSecond,1)}分後の予想血液null TI</span><strong class="value">${fmt(r.bloodNullTi)} ms</strong></div><div class="result-block"><span class="label">PSIR ${fmt(r.psirAfterSecond,1)}分後の予想心筋null TI</span><strong class="value">${fmt(r.psirNullTi)} ms</strong><div class="difference">TI scout正常心筋null TIとの差<br>${signed(r.psirVsScoutMyo)}</div><div class="difference">TI scout血液null TIとの差<br>${signed(r.psirVsScoutBlood)}<small>（TI scout正常心筋との差：${signed(r.scoutMyoVsBlood)}）</small></div></div>`;}
function heartSvg(myoSignal,bloodSignal){const m=grayscale(myoSignal,.5),b=grayscale(bloodSignal);return`<svg viewBox="0 0 360 240" role="img" aria-label="左室・右室短軸模式図"><path d="M196 40C105 32 45 78 55 143C63 198 123 218 190 185C166 157 161 83 196 40Z" fill="rgb(${b},${b},${b})" stroke="#555" stroke-width="3"/><ellipse cx="238" cy="120" rx="92" ry="94" fill="rgb(${m},${m},${m})" stroke="#464646" stroke-width="4"/><ellipse cx="238" cy="120" rx="50" ry="53" fill="rgb(${b},${b},${b})" stroke="#464646" stroke-width="3"/></svg>`;}
function renderIllustration(){const r=state.result,ti=state.displayTi;$("display-ti").value=ti;$("display-ti-value").textContent=`${fmt(ti)} ms`;$("display-ti-heading").textContent=`表示TI：${fmt(ti)} ms`;$("heart-illustration").innerHTML=heartSvg(signalAtTi(r.myocardialNullTi,ti),signalAtTi(r.bloodNullTi,ti));Plotly.relayout("signal-chart",{"shapes[0].x0":ti,"shapes[0].x1":ti});}
function renderChart(r){const m=signalCurve(r.myocardialNullTi),b=signalCurve(r.bloodNullTi);const traces=[{x:m.ti,y:m.signal,name:"正常心筋",mode:"lines",line:{color:"#1976b9",width:3}},{x:b.ti,y:b.signal,name:"血液",mode:"lines",line:{color:"#d33",width:3}}];const layout={margin:{l:58,r:20,t:45,b:55},xaxis:{title:"Inversion Time（TI）［ms］",range:[0,700],fixedrange:true},yaxis:{title:"正規化Magnitude信号［%］",range:[0,100],fixedrange:true},hovermode:"x unified",dragmode:false,shapes:[{type:"line",x0:state.displayTi,x1:state.displayTi,y0:0,y1:1,yref:"paper",line:{color:"#333",width:2,dash:"dot"}}],legend:{orientation:"h"}};Plotly.react("signal-chart",traces,layout,{responsive:true,displaylogo:false,scrollZoom:false,modeBarButtonsToRemove:["pan2d","zoom2d","select2d","lasso2d","zoomIn2d","zoomOut2d","autoScale2d"]});const chart=$("signal-chart");chart.removeAllListeners?.("plotly_click");chart.on("plotly_click",e=>{if(e.points?.length){state.displayTi=Math.round(e.points[0].x);renderIllustration();}});}
function renderGuide(r){const start=r.psirAfterSecond,times=[];for(let t=start;t<=15+1e-9;t+=1)times.push(t);const values=times.map(t=>{const c=myocardialConcentration(r.weight,1.5+t);return correctedNullTi(postContrastT1(r.nativeT1,c.total,5),57)}),base=values[0];$("guide-caption").textContent=`設定体重：${fmt(r.weight)} kgで計算した推定値です。`;$("psir-guide").innerHTML=`<thead><tr><th>項目</th>${times.map(t=>`<th>${Number.isInteger(t)?t:fmt(t,1)}分</th>`).join("")}</tr></thead><tbody><tr><td>設定TI目安</td>${values.map(v=>`<td>${fmt(v)} ms</td>`).join("")}</tr><tr><td>${Number.isInteger(start)?start:fmt(start,1)}分からの変化</td>${values.map((v,i)=>`<td>${i===0?"±0 ms":signed(v-base)}</td>`).join("")}</tr></tbody>`;}
function update(){try{$("error").textContent="";state.result=simulate(readInput());renderDose(state.result);renderPrimary(state.result);renderChart(state.result);renderIllustration();renderGuide(state.result);}catch(e){$("error").textContent=e.message;}}
Object.values(inputs).forEach(i=>i.addEventListener("input",update));$("display-ti").addEventListener("input",e=>{state.displayTi=Number(e.target.value);renderIllustration();});document.querySelectorAll("[data-shift]").forEach(b=>b.addEventListener("click",()=>{state.displayTi=Math.min(700,Math.max(0,state.displayTi+Number(b.dataset.shift)));renderIllustration();}));$("reset").addEventListener("click",reset);reset();
